#!/bin/sh
set -e

if [ $# -lt 2 ]; then
	echo "Usage: $0 <tag> <builder>" >&2
	exit 1
fi

tmpdir="$(mktemp -d --tmpdir build.XXXXXXX)"
trap 'sudo rm -rf "$tmpdir"' EXIT
export GIT_INDEX_FILE="$tmpdir/index"
export GIT_WORK_TREE="$tmpdir/build"

mkdir "$GIT_WORK_TREE"
git read-tree $1
git checkout-index -f -a
env --ignore-environment /usr/bin/sudo /usr/sbin/chroot "$GIT_WORK_TREE" $2 </dev/null
git add -A -f .
git write-tree
