#!/bin/sh
set -e

if [ $# -lt 2 ]; then
	echo "Usage: $0 <tag> <builder>" >&2
	exit 1
fi

tmpdir="$(mktemp -d --tmpdir build.XXXXXXX)"
trap 'sudo rm -rf "$tmpdir"' EXIT
export GIT_INDEX_FILE="$tmpdir/index"

./checkout-tree $1 "$tmpdir/build"
env --ignore-environment sudo chroot "$tmpdir/build" $2 </dev/null
git --work-tree="$tmpdir/build" add .
git write-tree
