#!/bin/sh
set -e

target="${2:-.}"
mkdir -p "$target"

# FIXME: use mktemp
export GIT_INDEX_FILE="$GIT_DIR/checkout-tree-index"
trap 'rm -f $GIT_INDEX_FILE' EXIT

git read-tree $1
git checkout-index -f -a --prefix="$target/"
