#!/bin/sh
set -e

prefix="$(echo $1 | tr '/' '\n' | tac)"
shift

for tree in "$@"
do
	tree=$(git rev-parse "$tree^{tree}")
	for d in $prefix
	do
		tree=$(printf "040000 tree $tree\t$d\n" | git mktree)
	done
	echo $tree
done
